### ISSUE TITLE
Про длину текста в Telegra.ph

### ISSUE THREAD

**Issue by MasterGroosha** [tginfo/Telegram-Limits#1]
На сайте [написано](https://limits.tginfo.me):

![изображение](https://user-images.githubusercontent.com/2780044/89643929-7dd9cb80-d8bf-11ea-9a04-60c05466e7a6.png)

Это не совсем так. Два примера:
https://telegra.ph/aa-08-07-7 (65 507 символов "f" + заголовок из двух английских "a")
https://telegra.ph/aa-08-07-8 (32 753 символа "ф"  + заголовок из двух английских "a")
Умножая 32 753 на 2, получаем 65 506, из чего можно сделать вывод, что лимит по тексту высчитывается не в количестве символов, а в килобайтах (кириллические символы занимают по два байта, в то время как латинские – по одному).
Итоговый лимит приблизительно равен 64 [кибибайтам](https://ru.wikipedia.org/wiki/%D0%9A%D0%B8%D0%B1%D0%B8%D0%B1%D0%B0%D0%B9%D1%82), а разница между 65507 и 65536 – метаданные, которые хранятся вместе с текстом.

**Comment by VectorASD** [comment]
https://telegra.ph/api#editPage
![Screenshot_290](https://github.com/tginfo/Telegram-Limits/assets/60642904/8179bc5d-a18b-48fa-9e09-ae5ac3a8641d)

Здесь можете почитать про API... На картинке явно видны эти 64 кб ;'-} т.е. даже ничего тестировать не нужно было кому-то :D Но про картинки ничего не сказано... скорее всего политика хранения медиа файлов от рандомных людей точно такая же, как и в самой телеге... чем чаще юзается медиа, тем выше шанс, что её не удалят, но как правило хранится минимум полгода, даже если это посмотрит полчеловека
