### ISSUE TITLE
Add "Max inline results per request = 50" in [Bots] category 

### ISSUE THREAD

**Issue by Muaath5** [tginfo/Telegram-Limits#107]
Add **`Max inline results per request =  50 inline result`**, Under _**Bots**_ category.

[The info source (For checking this info)](https://core.telegram.org/bots/api#answerinlinequery).

**Comment by Sominemo** [comment]
Thank you so much, I'll add it shortly

**Comment by New-dev0** [comment]
> Thank you so much, I'll add it shortly

With that, you can too limitatiom for Group Call Title - 64 Characters
