### ISSUE TITLE
Max number of emojis rendered with custom font

### ISSUE THREAD

**Issue by yashpalgoyal1304** [tginfo/Telegram-Limits#149]
there's a limit on number of emojis which can be used in a single message and are rendered by tg - exceeding that, the emoji rendering falls back to system emoji.

The limit was about 50 emojis per message, but i am not sure.

i am not even sure if this applies only to tgand or applies to other official clients too

**Comment by Sominemo** [comment]
That limit is actually unique per device and I'm not sure about the formula behind it

**Comment by yashpalgoyal1304** [comment]
with which devices u tried? i mean which android version and flavour they were running on? were any of them running on MIUI??

**Comment by Sominemo** [comment]
I conducted a little research, this limit is too complex and device-dependant to be included. The limit is 50 emojis, but only on Android < 7 and > 10.

**Comment by yashpalgoyal1304** [comment]
> but only on Android < 7 and > 10.

ahw, even that info is sooo good. thanks for sharing. i always used to wonder why telegram is soooo laggy with emojis on my older device. but this info confirmed it's cause.
