### ISSUE TITLE
using id or name for sections

### ISSUE THREAD

**Issue by yashpalgoyal1304** [tginfo/Telegram-Limits#150]
- accounts
- chats-and-groups
- voice-chats
- channels
- messages
- folders
- people-nearby
- bots
- search
- stickers
- telegraph
- miscellaneous

ref: https://www.w3schools.com/htmL/html_id.asp

![image](https://user-images.githubusercontent.com/19423063/131603168-ec2dcb53-b526-4e66-b137-290c1dfb5939.png)

**Comment by Sominemo** [comment]
I was considering it and it would be pretty hard to implement it just the way you want, so I didn't do it, considering complex dynamic layout. Instead, I made an option to jump to a search result link like this:
https://limits.tginfo.me/en/accounts
