### ISSUE TITLE
Sticker link character limit

### ISSUE THREAD

**Issue by artemetra** [tginfo/Telegram-Limits#160]
The character limit for a sticker id in a t.me/addstickers/(...) link is 62 characters

**Comment by om1ji** [comment]
`absolutely do not agree!!!` 
-16,000,000 social credits

**Comment by selurvedu** [comment]
@artemetra how do you know this? Also, do you happen to know the minimal length of a sticker/emoji pack name?

**Comment by artemetra** [comment]
1) Manual brute force search (trying to create a pack with 63 'A's fails).
2) The minimal length is 5.

**Comment by selurvedu** [comment]
@artemetra Thanks a lot!
