### ISSUE TITLE
Messaging rate limit incorrect

### ISSUE THREAD

**Issue by HeeroML** [tginfo/Telegram-Limits#192]
I'm pretty sure u know that already,but 30 messages a second is incorrect. It's 1 message every second to chats (groups/users/channels) with the  groups and channels having additional limits on top. But the 30req/s are definitely wrong and not defined by telegram. https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

Also only getMe and getUpdates aren't rate limited. All other requests are.

**Comment by Sominemo** [comment]
The limits were updated, thanks
