### ISSUE TITLE
exact Filesize limit

### ISSUE THREAD

**Issue by mrbesen** [tginfo/Telegram-Limits#213]
I found out the exact filesizelimit is `2097152000` Bytes (so its 2000 MiB, not 2GB or 2GiB).
Asuming the number used in tdlib is the same as the serverside limit.

This is my source:
An error is thrown when the file is bigger than `MAX_FILE_SIZE`: https://github.com/tdlib/td/blob/master/td/telegram/files/FileManager.cpp#L1007
which is defined here: https://github.com/tdlib/td/blob/master/td/telegram/files/FileManager.cpp#L56

I tested it by uploading a file exactly `2097152000` Bytes in size (worked)
and uploading a file exactly `2097152001` Bytes in size (failed).

It would be nice to have this exact limit listed on the Website. Maybe as mouseover-tooltip?
Same applies for the bot-api limits. 
The text "up to 2000 MB" is not correct. it would need to be "up to 2000 MiB"

BTW: the other limits are listed in that file as well: 
https://github.com/tdlib/td/blob/master/td/telegram/files/FileManager.cpp#L953-L955

**Comment by mrbesen** [comment]
"up to 2,000 MiB (slightly less than real 2 GB)"
is not quite right :(
"up to 2,000 MiB (slightly less than 2 **GiB** and slightly **more** than 2 **GB**)"
would be correct.

**Comment by Sominemo** [comment]
I specified "Real 2 GB" meaning 2 GiB. The limits website is not for techy people only and shouldn't confuse regular users that just search for limits in Google.

**Comment by mrbesen** [comment]
You are the Boss. But i think that dies can be more confusing. Because you always hear "telegram supports files up to 2GB". Now it sounds like it doesn't.
