### ISSUE TITLE
User can be spam banned for 1 day or more

### ISSUE THREAD

**Issue by evgfilim1** [tginfo/Telegram-Limits#217]
I wrote to SpamBot as soon as I noticed I cannot write non-contacts and in public groups, it was 19:34 UTC+5 (on screenshot)
![image](https://user-images.githubusercontent.com/17182159/171878656-46b15823-dc34-45a7-a6e2-4c511da104ad.png)

I don't know if this is still relevant, 5.5 years has passed since that ban. 
If this can be confirmed not only by me, you can change this line to `"1 day or more"`.
https://github.com/tginfo/Telegram-Limits/blob/8bd46e115b8221e7aae38e26fabd82e8e310b014/localization/en/data.json#L33

**Comment by Sominemo** [comment]
Closed in fc078fb998f93f9cfe7c8093374363fb4cc1665d
