### ISSUE TITLE
accounts number

### ISSUE THREAD

**Issue by DMJWorld** [tginfo/Telegram-Limits#3]
Add accounts that can be managed by the app:
**Accounts**
up to 3

**Comment by Sominemo** [comment]
> That's not correct. Telegram X for Android is the official app and it doesn't have accounts limit (at least there are 1000+)
> Maybe a tooltip can be added with a remark about tgx

We don't count Telegram X as an "official official" app I suppose, but I'll pass it further tomorrow to be discussed

**Comment by MasterGroosha** [comment]
Well, it's not listed under "unofficial apps" section, which makes it pretty much official.
https://telegram.org/apps#telegram-database-library-tdlib
https://telegram.org/blog/telegram-x
and finally https://twitter.com/telegram/status/1297910659775168514

**Comment by Sominemo** [comment]
> Well, it's not listed under "unofficial apps" section, which makes it pretty much official.
> https://telegram.org/apps#telegram-database-library-tdlib
> https://telegram.org/blog/telegram-x
> and finally https://twitter.com/telegram/status/1297910659775168514

That's why I used the "official official" term. Telegram X was born unofficially and later acquired by Telegram.

**Comment by Sominemo** [comment]
Требует слишком много телодвижений со стороны переводчиком для такого несущественного изменения.
