### ISSUE TITLE
Find user by adding a contact number limit

### ISSUE THREAD

**Issue by VitalyKrenel** [tginfo/Telegram-Limits#303]
Hey there! 

There's a flow to find some other users — when you add a phone number, then you can see the user [if they allowed it in the privacy].

<img width="428" alt="image" src="https://github.com/user-attachments/assets/560288be-f855-48e5-bbf8-b0b5f103de66">

I'm trying to figure out what the limits there, maybe @Sominemo knows or some other experienced folks around?

**Comment by VitalyKrenel** [comment]
@KnorpelSenf @EricKotato @AntonioMarreti @Sominemo folks, maybe someone still into this and could share some info? Googling and not finding much of valuable information on this kind of limits

**Comment by Sominemo** [comment]
There is no way to describe this limit by design because of its potential use by spammers
