### ISSUE TITLE
Tips for Video-avatar

### ISSUE THREAD

**Issue by DMJWorld** [tginfo/Telegram-Limits#4]
I suggest this change:
Video-avatar duration
up to 10 seconds

into

Video-avatar (for chats profile and channels)
up to 10 seconds, 800x800, max 2Mb

**Comment by Sominemo** [comment]
> (for chats profile and channels)
Hello,
I feel like thus part is not needed

**Comment by Sominemo** [comment]
Fixed in af71d8f
