### ISSUE TITLE
Fix minimal number of users to see stats in channel 

### ISSUE THREAD

**Issue by evgfilim1** [tginfo/Telegram-Limits#52]
![image](https://user-images.githubusercontent.com/17182159/97807439-910ff380-1c82-11eb-87c5-e6d77bddf877.png)
Valid limit is 50 ([source](https://t.me/tginfoen/1007))

**Comment by evgfilim1** [comment]
Not fixed yet

**Comment by Sominemo** [comment]
What do you mean?

**Comment by evgfilim1** [comment]
> What do you mean?

It's still 500 on the site

**Comment by Sominemo** [comment]
@evgfilim1 no, it isn't, read twice:
 https://limits.tginfo.me/en/Number%20of%20subscribers%20to%20see%20statistics

**Comment by evgfilim1** [comment]
Ah, sorry, I was reading it in "Chats" section, not "Channels"
